import pandas as pd
from pathlib import Path

for f in list(Path(".").glob("*.csv")):
    df = pd.read_csv(f)

    # Columns copied from original dataset. Other columns generated by authors or models
    df : pd.DataFrame = df.drop(['Question', 'Correct_Answer_Text'], axis=1)
    
    new_fname = f.with_suffix('.parquet')

    df.to_parquet(new_fname)